In [3]:
import pandas as pd

data = pd.read_csv('data.csv', sep='\t')
data.head()

,_id,cursor,timestamp,xpos,ypos,key,event,user,session_id
0,5e4a50654d1e4ccaca5d77d7,0,2020-02-17 08:35:44.485,343.0,65.0,0,mousemove,Alluserspreauth,366758616
1,5e4a50654d1e4ccaca5d77d8,0,2020-02-17 08:35:44.785,1010.0,436.0,0,mousemove,Alluserspreauth,366758616
2,5e4a50654d1e4ccaca5d77d9,0,2020-02-17 08:35:44.985,894.0,628.0,0,mouseout,Alluserspreauth,366758616
3,5e4a50654d1e4ccaca5d77da,0,2020-02-17 08:35:45.187,884.0,645.0,0,mousemove,Alluserspreauth,366758616
4,5e4a50654d1e4ccaca5d77db,0,2020-02-17 08:35:45.392,879.0,645.0,0,mousemove,Alluserspreauth,366758616

In [4]:
data.describe()

         cursor           xpos           ypos            key    session_id
count  142691.0  142691.000000  142691.000000  142691.000000  1.426910e+05
mean        0.0     119.159015      82.726934      57.044025  3.668589e+08
std         0.0     303.910797     203.473011      42.724058  8.357092e+04
min         0.0       0.000000       0.000000       0.000000  3.667586e+08
25%         0.0       0.000000       0.000000       0.000000  3.667711e+08
50%         0.0       0.000000       0.000000      83.000000  3.668420e+08
75%         0.0       0.000000       0.000000      95.000000  3.669232e+08
max         0.0    2405.000000    1287.000000     124.000000  3.670126e+08

In [29]:
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense, Concatenate

keyboard_input = Input(shape=(X_train_keyboard.shape[1],), name="keyboard_input")
keyboard_dense = Dense(64, activation="relu")(keyboard_input)

mouse_input = Input(shape=(X_train_mouse.shape[1],), name="mouse_input")
mouse_dense = Dense(128, activation="relu")(mouse_input)

merged = Concatenate(name="merged_layer")([keyboard_dense, mouse_dense])
output = Dense(1, activation="sigmoid", name="output")(merged)

model = Model(inputs=[keyboard_input, mouse_input], outputs=output)
model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])
model.summary()

Model: "functional_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                  ┃ Output Shape              ┃         Param # ┃ Connected to               ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ keyboard_input (InputLayer)   │ (None, 26)                │               0 │ -                          │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ mouse_input (InputLayer)      │ (None, 3)                 │               0 │ -                          │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ dense_8 (Dense)               │ (None, 64)                │           1,728 │ keyboard_input[0][0]       │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ dense_9 (Dense)               │ (None, 128)               │             512 │ mouse_input[0][0]          │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ merged_layer (Concatenate)    │ (None, 192)               │               0 │ dense_8[0][0],             │
│                               │                           │                 │ dense_9[0][0]              │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ output (Dense)                │ (None, 1)                 │             193 │ merged_layer[0][0]         │
└───────────────────────────────┴───────────────────────────┴─────────────────┴────────────────────────────┘

 Total params: 2,433 (9.50 KB)

 Trainable params: 2,433 (9.50 KB)

 Non-trainable params: 0 (0.00 B)

In [54]:
from sklearn.utils import resample

X_train_mouse_resampled = X_train_mouse[:len(X_train_keyboard)]
y_train_mouse_resampled = y_train_mouse[:len(X_train_keyboard)]